// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoIqVWQRUXnzYtAQtz90-avgJy0xKnHoI',
    appId: '1:441742205350:android:881464acbe22b8c0b32f67',
    messagingSenderId: '441742205350',
    projectId: 'welldonated',
    storageBucket: 'welldonated.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGWFZT1GZDEPvztvvpWhCwfVGhvBzoISg',
    appId: '1:441742205350:ios:fa4775e5dab9c07ab32f67',
    messagingSenderId: '441742205350',
    projectId: 'welldonated',
    storageBucket: 'welldonated.appspot.com',
    iosClientId: '441742205350-ri1qcm0da6kk0n1tch68d7vmj4drsttg.apps.googleusercontent.com',
    iosBundleId: 'com.example.welldonatedproject',
  );
}
